{print} = require 'sys'
{spawn} = require 'child_process'

build = (options)->
  coffee = spawn 'coffee.cmd', options
  coffee.stderr.on 'data', (data) ->
    process.stderr.write data.toString()
  coffee.stdout.on 'data', (data) ->
    print data.toString()

task 'server-build', 'Build lib/ from src/', ->
  build ['-c', '-o', 'lib', 'src']

task 'client-build', 'Build lib/ from src/', ->
  build ['-w', '-c', 'public']