{print} = require 'sys'
{spawn} = require 'child_process'

build = ->
  coffee = spawn 'coffee.cmd', ['-c', '-m', '-o', 'lib', 'src']
  coffee.stderr.on 'data', (data) ->
    process.stderr.write data.toString()
  coffee.stdout.on 'data', (data) ->
    print data.toString()

task 'build', 'Build lib/ from src/', ->
  build()